In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [3]:
from sklearn.datasets import make_classification


In [4]:
X,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [5]:
X.shape,y.shape

((1000, 10), (1000,))

In [6]:
X

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]])

In [7]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [8]:
pd.DataFrame(X)


0         1         2  ...         7         8         9
0    0.964799 -0.066449  0.986768  ... -1.210161 -0.628077  1.227274
1   -0.916511 -0.566395 -1.008614  ... -0.984534  0.363896  0.209470
2   -0.109484 -0.432774 -0.457649  ... -0.246383 -1.058145 -0.297376
3    1.750412  2.023606  1.688159  ... -0.357445 -1.473127 -0.190039
4   -0.224726 -0.711303 -0.220778  ... -0.939156  0.175915  0.236224
..        ...       ...       ...  ...       ...       ...       ...
995 -1.367638  1.462255 -1.154918  ...  1.428760  1.687092  1.072542
996 -1.514876 -3.221016 -1.300744  ... -1.680870  1.798510  0.034272
997  1.674633  1.754933  1.586154  ...  0.692723 -1.503850  0.225264
998 -0.778609 -0.835689 -0.194842  ... -0.497354  2.472138  0.867187
999  0.248454 -1.003439  0.360460  ...  0.773240  0.185734  1.416412

[1000 rows x 10 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [10]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()


In [11]:
log_model.fit(X_train, y_train),
y_pred = log_model.predict(X_test)

y_pred

In [12]:
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1])

In [13]:
log_model.predict_proba(  X_test)

array([[7.78600959e-01, 2.21399041e-01],
       [3.19099883e-02, 9.68090012e-01],
       [6.42146681e-01, 3.57853319e-01],
       [7.47380192e-02, 9.25261981e-01],
       [9.75407948e-01, 2.45920523e-02],
       [3.99148910e-02, 9.60085109e-01],
       [9.78737182e-01, 2.12628178e-02],
       [9.52833227e-01, 4.71667733e-02],
       [7.87837418e-01, 2.12162582e-01],
       [6.81333736e-01, 3.18666264e-01],
       [9.15901071e-01, 8.40989288e-02],
       [2.42589360e-01, 7.57410640e-01],
       [5.03410713e-01, 4.96589287e-01],
       [1.92363097e-01, 8.07636903e-01],
       [7.93085129e-01, 2.06914871e-01],
       [9.43576898e-01, 5.64231015e-02],
       [2.69367304e-02, 9.73063270e-01],
       [3.41710994e-01, 6.58289006e-01],
       [3.08678280e-01, 6.91321720e-01],
       [1.74169127e-01, 8.25830873e-01],
       [4.84677714e-01, 5.15322286e-01],
       [9.62607338e-01, 3.73926615e-02],
       [1.81990356e-01, 8.18009644e-01],
       [7.82536737e-01, 2.17463263e-01],
       [8.635545

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,precision_score, recall_score, f1_score
print(accuracy_score(y_test, y_pred)),
print(confusion_matrix(y_test, y_pred)),
print(classification_report(y_test, y_pred)),
print(precision_score(y_test, y_pred), recall_score(y_test, y_pred), f1_score(y_test, y_pred))


            


0.83
[[75 14]
 [20 91]]
              precision    recall  f1-score   support

           0       0.79      0.84      0.82        89
           1       0.87      0.82      0.84       111

    accuracy                           0.83       200
   macro avg       0.83      0.83      0.83       200
weighted avg       0.83      0.83      0.83       200

0.8666666666666667 0.8198198198198198 0.8425925925925926


HyperParameter Tuning


In [15]:
log_model_tuning = LogisticRegression()
penalty = ['l1', 'l2', 'elasticnet', 'none']
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
c = [0.001, 0.01, 0.1, 1, 10, 100]


In [20]:
params = dict(penalty=penalty, solver=solver, C=c)

In [21]:
params

{'penalty': ['l1', 'l2', 'elasticnet', 'none'],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
 'C': [0.001, 0.01, 0.1, 1, 10, 100]}

In [26]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(log_model_tuning, params, cv=5, scoring='accuracy', verbose=1)


In [28]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

Fitting 5 folds for each of 120 candidates, totalling 600 fits


/Library/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: Con

{'C': 0.01, 'penalty': 'l2', 'solver': 'liblinear'}

In [29]:
from sklearn.model_selection import RandomizedSearchCV
model = LogisticRegression()

In [30]:
model.fit(X_train, y_train)
random_search = RandomizedSearchCV(model, params, n_iter=10, cv=5, scoring='accuracy', verbose=1, random_state=42)
random_search.fit(X_train, y_train)
random_search.best_params_
# Using the best parameters from grid search

Fitting 5 folds for each of 10 candidates, totalling 50 fits


/Library/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
20 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/Library/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Library/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/Library/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/Library/anaconda3/lib/p

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.01}

In [31]:
random_search.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.01}

In [32]:
random_search.best_score_

0.8787499999999999

In [34]:
y_pred = random_search.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_pred = log_model.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.83
