In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000,
                         n_features=3,
                         n_redundant=1,
                         n_classes=2,
                         random_state=999)
X,y

(array([[-0.33504974,  0.02852654,  1.16193084],
        [-1.37746253, -0.4058213 ,  0.44359618],
        [-1.04520026, -0.72334759, -3.10470423],
        ...,
        [-0.75602574, -0.51816111, -2.20382324],
        [ 0.56066316, -0.07335845, -2.15660348],
        [-1.87521902, -1.11380394, -4.04620773]]),
 array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
        0, 1, 1, 1, 1, 1,

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,random_state=43)

In [8]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((750, 3), (250, 3), (750,), (250,))

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(algorithm='auto')
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[123  11]
 [ 11 105]]
              precision    recall  f1-score   support

           0       0.92      0.92      0.92       134
           1       0.91      0.91      0.91       116

    accuracy                           0.91       250
   macro avg       0.91      0.91      0.91       250
weighted avg       0.91      0.91      0.91       250



Regression


In [26]:
from sklearn.datasets import make_regression
X,y = make_regression(n_samples=1000,
                         n_features=2,
                         noise=2,
                         random_state=999)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,random_state=43)


In [34]:
from sklearn.neighbors import KNeighborsRegressor
knnr = KNeighborsRegressor(n_neighbors=5,algorithm='auto')
knnr.fit(X_train,y_train)
y_pred1 = knnr.predict(X_test)
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred1))



0.9917119517374889
